name             'openstack'
maintainer       'Vinícius Kirst'
maintainer_email 'vinicius.kirst@gmail.com'
license          'All rights reserved'
description      'Installs/Configures openstack'
long_description 'Installs/Configures openstack'
version          '0.1.0'

depends 'apt'
depends 'chrony'
depends 'rabbitmq'
depends 'mysql', '~> 6.0'
depends 'mysql2_chef_gem'
depends 'database'
depends 'hostsfile'
depends 'mongodb'
